version: '2'
services:
  mysql:
        image: mysql:5.7
        environment:
           - MYSQL_ROOT_PASSWORD=password
           - MYSQL_DATABASE=demo
           - MYSQL_USER=demo_user
           - MYSQL_PASSWORD=demo_pass
        ports:
            - 3306:3306
            
  test-backend:
     image: "sopheamak/springboot_docker_mysql"
     restart: always
     links:
      - mysql:mysql
     ports:
         - 8080:8080
     environment:
            - DATABASE_HOST=mysql
            - DATABASE_USER=root
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=demo
            - DATABASE_PORT=3306
 
